### ISSUE TITLE
Async/Await support

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.SqlServer#100]
Task force: @tmasternak @weralabaj @justabitofcode @mauroservienti
Make changes to Sql Transport that will make it possible to use it with NServiceBus v6

### Impact assessment  
Any user who uses sql transport and will want to migrate to v6.

### Plan of Attack

- Features
 - ~~[Transactions support](https://github.com/Particular/NServiceBus.SqlServer/issues/138)~~ (done)
 - [Multi-database support](https://github.com/Particular/NServiceBus.SqlServer/issues/139) 
 - ~~[Multi-schema support](https://github.com/Particular/NServiceBus.SqlServer/issues/140)~~ (done)
 - ~~[TTBR](https://github.com/Particular/NServiceBus.SqlServer/issues/141)~~ (done)
 - ~~[Auto-creation of db structure](https://github.com/Particular/NServiceBus.SqlServer/issues/142)~~ (done)
- Testing
 - ~~[Acceptance tests from core, SqlTransport v2 and new for v3](https://github.com/Particular/NServiceBus.SqlServer/issues/130)~~ (done)
 - ~~[Performance testing](https://github.com/Particular/NServiceBus.SqlServer/issues/125)~~ (out-of-scope)
 - ~~[Wirecompat test](https://github.com/Particular/NServiceBus.SqlServer/issues/131)~~ (done)
 - ~~[Callback receivers](https://github.com/Particular/NServiceBus.SqlServer/issues/132)~~ (done)
- Documentation
 - ~~[Smoke tests for doc content](https://github.com/Particular/NServiceBus.SqlServer/issues/133)~~
 - ~~[Upgrade guide](https://github.com/Particular/NServiceBus.SqlServer/issues/134) https://github.com/Particular/docs.particular.net/issues/1195~~
 - ~~[Multi-schema v3 to v1/v2 setup guide](https://github.com/Particular/NServiceBus.SqlServer/issues/135)~~ (not relevant anymore)
 - ~~[Connection pool guidance](https://github.com/Particular/NServiceBus.SqlServer/issues/136)~~
 - ~~[Update docs](https://github.com/Particular/NServiceBus.SqlServer/issues/137)~~ (done)
 - ~~[Update samples](https://github.com/Particular/docs.particular.net/issues/1010)~~ : ~~need to be updated and tested after related bugs are resolved- https://github.com/Particular/NServiceBus/issues/3499, https://github.com/Particular/NServiceBus.NHibernate/issues/161~~ (done).
- ~~Doco multiinstance https://github.com/Particular/NServiceBus.SqlServer/pull/161/files#r53755702~~

- [x] Async review @danielmarbach
- [ ] Retrospective
- [ ] After all ABOVE is finished: update references in samples and docs + verify all still works
    - [ ] http://docs.particular.net/samples/sqltransport/native-integration/
    - [ ] http://docs.particular.net/samples/msmqtosqlrelay/
    - [ ] http://docs.particular.net/samples/outbox/sqltransport-nhpersistence/
    - [ ] http://docs.particular.net/samples/outbox/sqltransport-nhpersistence-ef/
    - [ ] https://github.com/Particular/ProductionTests/tree/master/src/TransportCompatibilityTests

### Related known issues:
- [Multi-database setup physical address automatic (connection-string) management](https://github.com/Particular/PlatformDevelopment/issues/486)
- ~~[Wire-compat tests](https://github.com/Particular/NServiceBus.SqlServer/issues/98)~~(solved)
- ~~[Message id format](https://github.com/Particular/NServiceBus.SqlServer/issues/74)~~ (solved)

Connects to [Transports for v6](https://github.com/Particular/NServiceBus/issues/3125)

**Comment by weralabaj** [comment]
@mauroservienti @justabitofcode is there anything I could do to help you with pushing multi-db/mulit-instance forward (code, docs, whatever...)?

**Comment by danielmarbach** [comment]
@Particular/transport-maintainers since all outstanding issues are tracked should we close this one?

**Comment by tmasternak** [comment]
@weralabaj I think we need to track retrospective somewhere else. Are we tracking sample updates separately in docs?

**Comment by mauroservienti** [comment]
>  I think we need to track retrospective somewhere else

why? we tried that and get back to include the retrospective in the original issue

**Comment by tmasternak** [comment]
@mauroservienti The reason why in my opinion it makes sense to move out of this one is visibility. Right now when I look at the issues in repo I already skip this as it brings no value in terms of figuring out what's left. The assumption was if this is colsed we are ready for V6 but we can equaly state that if there is no issue with V6 label we are done.

**Comment by weralabaj** [comment]
The only thing that is not finished is related to multi-db, we track it with a separate issue.
I'm ok with whatever is more convenient for squad, we can schedule retro now and close it?
I think we won't wait for the v3-v2 pub sub bug right?

**Comment by tmasternak** [comment]
> I think we won't wait for the v3-v2 pub sub bug right?
:+1:

**Comment by mauroservienti** [comment]
I disagree :smile:, but seems that I'm the minority. So let's close this and open an issue for the retrospective. Are we going to have a retrospective for the v3-v2 pub sub bug?

**Comment by weralabaj** [comment]
@mauroservienti I think we should discuss it during this retro too. Even if we don't have a fix yet.

**Comment by weralabaj** [comment]
I've scheduled retro. Closing this issue.

**Comment by mauroservienti** [comment]
Why are we closing the issue if the retrospective is not happened yet?
Are all the doco stuff done?

**Comment by tmasternak** [comment]
@mauroservienti sorry for misunderstanding. But what I thought is that we don't want to keep this one around when we have other issues that cover PoA from this one.

**Comment by mauroservienti** [comment]
Wasn't this behaving as an umbrella for dependent task?
Didn't the squad this morning decided that umbrella issues must be updated with details of the on going progress in dependent tasks?

**Comment by tmasternak** [comment]
@mauroservienti My understanding was that the decission was: "If the umbrella task exists ... "

**Comment by mauroservienti** [comment]
OK, got it.

**Comment by weralabaj** [comment]
@mauroservienti I closed that issue last week, so it might conflict with the decision from today's morning :) We can reopen it if needed, the confusion we wanted to address was having the same thing tracked in multiple issues.
Retro is scheduled for next week.
