### ISSUE TITLE
SQL v3: Multi-instance support

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.SqlServer#139]
Task force: @tmasternak @weralabaj @justabitofcode @mauroservienti @SzymonPobiega 

## Summary
**We decided to drop the multi-instance support for the V3 of the SQL Transport.**
Being a major release we could drop the feature without any concern, but we want to provide customers using it an exit strategy. We actually have a working spike that enables the multi-instance support as it was in V2, **we decided to ship it as a sample in our documentation**.

Along with this decision we also strongly think that we should release a set of guidance on why multi-instance is a bad design decision and how to implement shovel-like solutions in a SQL transport based topology.

## Plan of Attack
- [x] Provide legacy multi-instance mode custom connection factory
- [x] Create sample showing how to set it up => @justabitofcode 
   - [x] Add v5 version https://github.com/Particular/docs.particular.net/pull/1359
- [x] Update doco on multi-database => @weralabaj https://github.com/Particular/docs.particular.net/pull/1346
   - [x] Document `Queue Schema=` in Connection String for Sql Transport  https://github.com/Particular/docs.particular.net/issues/1304
   - [x] Remove all "multi-database" expressions, replace with either "multi-catalog" or "multi-instance"
   - [x] Guidance on when to use each, list advantages and disadvantages (remember about https://github.com/Particular/docs.particular.net/pull/1206#discussion_r54778922)
   - [x] Explain that we require DTC enabled now (https://github.com/Particular/NServiceBus.SqlServer/pull/161/files#r53755702)
- [x]  Upgrade guide for multi-instance @weralabaj
- [x] ~~Update exception message ttps://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Legacy/MultiInstance/LegacySqlServerTransportInfrastructure.cs#L51~~ After recent changes in doco we don't need to change it, it's consistent with vocabulary used in doco (comment by @weralabaj)
- [x] Update sample with Multi-instance + Outbox in v5 and link to explanation why it's not longer supported https://github.com/Particular/docs.particular.net/issues/1168
- [x] ~~Documentation/Guidance around security ??~~ Moved to https://github.com/Particular/docs.particular.net/issues/1347.
- [x] Update messages on obsoleted members (they're imprecise) https://github.com/Particular/NServiceBus.SqlServer/pull/194
- [x] Retrospective (scheduled for Tue 5th Apr)

Related to #100

**Comment by mauroservienti** [comment]
We decided to drop the multi-instance support for the V3 of the SQL Transport.
Being a major release we could drop the feature without any concern, but we want to provide customers using it an exit strategy. We actually have a working spike that enables the multi-instance support as it was in V2, we are faced with 3 options:

1. Release it as an unsupported sample that explain to customers how to build that feature on their own
* Release it as a downstream Nuget package that extends the transport configuration with the legacy options
* Release it as part of the transport itself adding a configuration option, such as an appSetting, to enable it

The last one appears to be the most interesting, cause theoretically it enables the transport to work in ServiceControl as well without any change to ServiceControl. We now know that it is not true, actually ServiceControl crashes when using the SQL transport and the multi-instance due to some expectations in ServiceControl not met by the transport, this raises the issue that the transport may have an opinion on the ServiceControl configuration, if we fix this then option (2) is the best in my opinion since from the user perspective an official package is much better than a sample and from our perspective it may end up having a different support life cycle.

Along with this decision we also strongly think that we should release a set of guidance on why multi-instance is a bad design decision and how to implement shovel-like solutions in a SQL transport based topology.

We think that the async transport task force should only be responsible of:

* making the decision
* listing options to move forward
* spiking any shovel-like implementation
* highlighting ServiceControl issues

**Comment by ramonsmits** [comment]
@mauroservienti Till now I've only read multi instance is dropped and not multi database but both are not supported I guess?

Lets get our vocabulary straight and use SQL Server terminology:

- Server, The host
- Instance, The SQL process. Can have multple on a single server
- Catalog, The database. Can have multiple on a single instance
- Schema, The schema. Can have multiple in a single catalog

When saying multi database we basicallly say multi catalog is not supported and that indirectly implies multi instance is not supported too.

As I've advocated in #113 I would favor adding catalog and schema identifiers in the queue names. That would make it very easy to support both multi schema and multi catalog while sharing the same / a single connection string. It needs no trickery by defining a schema and/or catalog mapping somewhere as this is the native format of the transport and is readable by any DBA.

What would be wrong with supporting fully qualified names name like [Sales]..[OrderProcessing] ?

Is such a a queue name too coupled to the transport? Is it that we only want to use 'logical' queues and not physical?

**Comment by mauroservienti** [comment]
@ramonsmits we never had a distinction between multi-instance and multi-database, but I think that could be interesting to support the multi-database scenario.

@tmasternak thoughts?

**Comment by ramonsmits** [comment]
@mauroservienti No I understand as previously we had the mindset to only access a single database on a sql connection (string) but that is restriction we set ourselves.

**Comment by tmasternak** [comment]
I think that I makes sense to support this. On a technical level what @ramonsmits proposes should not be a problem. I need to verify if we can do it in backwards compatible way but I think it should work.

@mauroservienti: should I create an issue for that. It can probably be just a spike to figure out if we can do it later for 3.1.

**Comment by mauroservienti** [comment]
Yes let's create a separate issue and consider it for the next minor.

**Comment by tmasternak** [comment]
I'm still working on extension point PR. Should be ready this week.

**Comment by tmasternak** [comment]
This is work in progress. We are working on legacy multi-instance code sample //cc: @justabitofcode

**Comment by tmasternak** [comment]
I've cleaned up the issue removing the non-core v6 items.

**Comment by weralabaj** [comment]
Regarding "Documentation/Guidance around security" I think that should be raised as a separate issue in docs. It's not specifically V6 related.

**Comment by tmasternak** [comment]
We are waiting for doc PR to get merged and this one is done.

**Comment by SimonCropp** [comment]
@tmasternak can u link to the docs PR

**Comment by tmasternak** [comment]
@SimonCropp I've added PoC for the docs issue that is already linked (the only outstanding in PoC here)

**Comment by mauroservienti** [comment]
Will this be included in the retrospective we already scheduled?

**Comment by weralabaj** [comment]
@mauroservienti Of course, that was part of that bigger task & the same TF, so I think we should do it together.

**Comment by weralabaj** [comment]
According to today's discussion - I'm reopening this issue for retrospective.

**Comment by tmasternak** [comment]
Removing the `In Progress` - this has not been scheduled. 
@weralabaj I think that we should close this one and add `Consider for Promotion` the retrospective one.

**Comment by weralabaj** [comment]
What has not been scheduled? Should I re-open the other issue? Or open a new issue just for retrospective and cancel our meeting for now until squad prioritizes?

**Comment by tmasternak** [comment]
I think the latter one.

**Comment by weralabaj** [comment]
I don't understand the reasoning behind this. I prematurely closed the issue - ok, my bad, I apologized and I reopened it for retro. Luckily for me, the WIP limit allows for going back at the moment.
So now we're risking that retro won't happen at all? How is that actually adding any value? And for whom?

**Comment by weralabaj** [comment]
Hard not to think that I'd be better off not following the process, and making retro without making it visible. "Stupid me for following the process" seems to be the message, I don't think this is what we're trying to get across. Or we just don't care about retros anymore?

**Comment by indualagarsamy** [comment]
Currently we have users who use the multi-instance / multi-catalog support.  
@Particular/sqlserver-transport-maintainers - Please review this case https://nservicebus.desk.com/agent/case/18278 and answer the user.
