### ISSUE TITLE
Make native integration easier

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#178]
## Goal

The goal of this task is to make changes to SqlServer table schema to make the native integration easier.
It groups other issues which have been created separately.
Those changes should be implemented in such a way that **wire compatibility** with older versions is preserved.  
Potential changes:
- [ ] Make the Id column a IDENTITY instead of `UniqueIdentifier`. Details: #74 
- [ ] Make the headers column nullable. Details: #73
- [ ] Make the `Recoverable` column default to true. Details #71

**Comment by MarcinHoppe** [comment]
Would the new schema apply only to endpoints created with transport with this feature implement or are we actually thinking about migrating schemas of existing queue tables?

**Comment by tmasternak** [comment]
@MarcinHoppe TBH I don't know :/. Ideally users should not care which means new endpoints just work with the old once. I know that one of the discussed options where `updatable views` but not decision was made. 

I think that either way any changes to table schema should probably be postponed until we figure out the best approach to multi-instance support #139. One of the options there is to provide some kind on synchronization process and that might be a good moment to figure out possibilities for changing the schema.

**Comment by mauroservienti** [comment]
Closed in favor of #179 that will have to deal with how to evolve the schema.
